//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public int ID { get; set; }
        public string TenChuongTrinh { get; set; }
        public string MaKM { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public int SoTienKM { get; set; }
        public int SoTienMuaHangToiThieu { get; set; }
        public int SoLanDung { get; set; }
        public bool KichHoat { get; set; }
    }
}
