//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phanquyen
    {
        public int AdminID { get; set; }
        public string Email { get; set; }
        public string Matkhau { get; set; }
        public int Quyen { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<bool> Trangthai { get; set; }
    }
}
