//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONHANG = new HashSet<CHITIETDONHANG>();
            this.DANHGIA = new HashSet<DANHGIA>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string MoTa { get; set; }
        public string TacGia { get; set; }
        public string Anh { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public int SoLuongBan { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> MaNVTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIA { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
